# ALL THE APPLICATION CONSTANTS

ADDON_PREFIX = 'ESEC'
ADDON_NAME = 'Floorplan_Creator'
ICONS_DIRECTORY = 'icons'
MODELS_LOW_DIRECTORY = 'models_low'
MODELS_HIGH_DIRECTORY = 'models_high'
HDRI_DIRECTORY = 'hdri'
PIP_PACKAGES = []
